### ISSUE TITLE
Add SLD option to the mafile redirect

### ISSUE THREAD

**Issue by epifanio** [metno/mapgen-fastapi#20]
Mapserver can consume -  SLD - as URL parameter, will be good to have this option exposed to the mapfile redirect API.

The SLD parameter can be used in a `GetMap` request (SLD options are ignored by the `GetCapabilities`) - the requirements for a `GetMap` request are:

- map layer 
- layer CRS and Extent (BBOX)
- layer name
- image format
- image size (Width, Height)

Map layers, CRS, and Extent can be extracted directly from a data source ([issue 21](https://github.com/metno/mapgen-fastapi/issues/21))

Image format and image sizes are user/application defined parameters (independent from the datasource)

**Comment by TAlonglong** [comment]
WE need to clean up here @epifanio . Does this still apply or can we close this now to be reopened when needed?

**Comment by TAlonglong** [comment]
WE ended up not using SLD for the current solutions. Will close this now and create a new issue if we need SLD in the future
