### ISSUE TITLE
add a method to extract information from a datasource

### ISSUE THREAD

**Issue by epifanio** [metno/mapgen-fastapi#21]
There are a number of pieces of information, e,g,

- variable names
    - check variables names and units with CF convention (cold be used to choose from a pre-defined color map: e,g.: temperature/ celsius)
    - data range for each variable (could be used to build custom color maps)
- geographic extent and CRS

 That can be extracted from a data source and used when filling a mapfile template, and/or when building a `GetMap` request.
 
 Will be good to have a generic method for this purpose that can extract that information directly from a data source URL.

**Comment by TAlonglong** [comment]
This does not apply anymore.
