### ISSUE TITLE
build SLD from templates

### ISSUE THREAD

**Issue by epifanio** [metno/mapgen-fastapi#23]
The SLD style refers to a specific layer which can not be hardcoded in a SLD file. We can use a SLD template to fill in the required information and serve the result as a [file response](https://fastapi.tiangolo.com/advanced/custom-response/#fileresponse)

**Comment by TAlonglong** [comment]
WE need to clean up here @epifanio . Does this still apply or can we close this now to be reopened when needed?

**Comment by TAlonglong** [comment]
WE ended up not using SLD for the current solutions. Will close this now and create a new issue if we need SLD in the future
