### ISSUE TITLE
Try standard name as default title or layer name

### ISSUE THREAD

**Issue by mortenwh** [metno/mapgen-fastapi#71]
https://github.com/metno/mapgen-fastapi/blob/24bdc05cad2671458d37b4991041bb018557b634/mapgen/modules/helpers.py#L461-L467

Could we do: `wms_title += f": {ds[variable].attrs['standard_name']}"` instead?

Or is it `layer.name = variable` that should be `layer.name = f"{ds[variable].attrs['standard_name']}"` as first option, and fallback to `variable`? This in order to use `standard_name` in the layer list in MMD...

**Comment by TAlonglong** [comment]
How would you find the corresponding variable:

`ncdump -h /lustre/storeA/project/metproduction/products/meps/meps_det_vdiv_2_5km_20240926T09Z.nc |grep standard_name | grep air_temperature`
```
		air_temperature_0m:standard_name = "air_temperature" ;
		air_temperature_pl:standard_name = "air_temperature" ;
		air_temperature_z:standard_name = "air_temperature" ;
		air_temperature_2m:standard_name = "air_temperature" ;
		tropopause_air_temperature:standard_name = "tropopause_air_temperature" ;
		air_temperature_max:standard_name = "air_temperature" ;
		air_temperature_min:standard_name = "air_temperature" ;
		SFX_X001T2M_P:standard_name = "air_temperature" ;
		SFX_X002T2M_P:standard_name = "air_temperature" ;
		SFX_TS:standard_name = "air_temperature" ;
		SFX_T2M:standard_name = "air_temperature" ;
```

**Comment by mortenwh** [comment]
ah - I didn't think about that.. then, I guess we need to use the variable names in `nc_to_mmd` - I'll add an issue and try to solve it quickly.
